In [2]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

X_train = [[6], [8], [10], [14], [18]]
y_train = [[7], [9], [13], [17.5], [18]]
X_test = [[6], [8], [11], [16]]
y_test = [[8], [12], [15], [18]]

# linear model
regressor = LinearRegression()
regressor.fit(X_train, y_train)
xx = np.linspace(0, 26, 100)
yy = regressor.predict(xx.reshape(xx.shape[0], 1))
plt.plot(xx, yy)

# quadratic model
quadratic_featurizer = PolynomialFeatures(degree=2)
X_train_quadratic = quadratic_featurizer.fit_transform(X_train)
X_test_quadratic = quadratic_featurizer.transform(X_test)
regressor_quadratic = LinearRegression()
regressor_quadratic.fit(X_train_quadratic, y_train)
xx_quadratic = quadratic_featurizer.transform(xx.reshape(xx.shape[0], 1))
plt.plot(xx, regressor_quadratic.predict(xx_quadratic), c='r', linestyle='--')

# cubical modle
cube_featurizer = PolynomialFeatures(degree=3)
X_train_cube = cube_featurizer.fit_transform(X_train)
X_test_cube = cube_featurizer.transform(X_test)
regressor_cube = LinearRegression()
regressor_cube.fit(X_train_cube, y_train)
xxx_cube = cube_featurizer.transform((xx.reshape((xx.shape[0], 1))))
plt.plot(xx, regressor_cube.predict(xxx_cube), c='r')

plt.title('Pizza price regressed on diameter')
plt.xlabel('Diameter in inches')
plt.ylabel('Price in dollars')
plt.axis([0, 25, 0, 25])
plt.grid(True)
plt.scatter(X_train, y_train)
plt.show()


print X_train
print'**********'
print X_train_quadratic
print'**********'
print X_train_cube
print'**********'
print X_test
print'**********'
print X_test_quadratic
print'**********'
print  X_test_cube

print 'Simple linear regression r-squared', regressor.score(X_test, y_test)
print 'Quadratic regression r-squared', regressor_quadratic.score(X_test_quadratic, y_test)
print 'Cubic regression r-squared', regressor_cube.score(X_test_cube, y_test)


[[6], [8], [10], [14], [18]]
**********
[[  1.   6.  36.]
 [  1.   8.  64.]
 [  1.  10. 100.]
 [  1.  14. 196.]
 [  1.  18. 324.]]
**********
[[1.000e+00 6.000e+00 3.600e+01 2.160e+02]
 [1.000e+00 8.000e+00 6.400e+01 5.120e+02]
 [1.000e+00 1.000e+01 1.000e+02 1.000e+03]
 [1.000e+00 1.400e+01 1.960e+02 2.744e+03]
 [1.000e+00 1.800e+01 3.240e+02 5.832e+03]]
**********
[[6], [8], [11], [16]]
**********
[[  1.   6.  36.]
 [  1.   8.  64.]
 [  1.  11. 121.]
 [  1.  16. 256.]]
**********
[[1.000e+00 6.000e+00 3.600e+01 2.160e+02]
 [1.000e+00 8.000e+00 6.400e+01 5.120e+02]
 [1.000e+00 1.100e+01 1.210e+02 1.331e+03]
 [1.000e+00 1.600e+01 2.560e+02 4.096e+03]]
Simple linear regression r-squared 0.809726797707665
Quadratic regression r-squared 0.8675443656345054
Cubic regression r-squared 0.835692415603711
